"""
adjudicate_deep5.py
===================
Amendment 6 Part B adjudication for the deep5 arm (5 hidden ReLUs).

Reuses the registered pipeline pieces (D_var, D_sheaf_B raw/PCA-64, D_logic
with the amendment-4 sanity gate, per-layer aux diagnostics, fourier
concentration, sharpening S-statistics) on the deep5 traces, plus a freshly
computed shallow concentration pool for D3.

Cost controls (disclosed in the output):
- Final-layer TIMING series are strided to every 2nd checkpoint when a trace
  has more than 1500 checkpoints (censored runs log 4000). The logistic
  timing metric is insensitive to 2x cadence; coverage/purity diagnostics
  additionally use the aux layers at their native cadence.
- The spectral (H4) observables are skipped: they are not part of the
  registered D1-D4 rules for this arm.

Usage:
    python scripts/adjudicate_deep5.py [--trace_dir data/phase2_traces_v2]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from grokking_scaling_theory.sheaf_order_parameter import (  # noqa: E402
    TraceArrays,
    project_pca,
    compute_order_parameters,
)
from grokking_scaling_theory.logical_cells import (  # noqa: E402
    d_logic_series,
    fourier_concentration,
)
from grokking_scaling_theory.order_parameter_compare import (  # noqa: E402
    d_var_series,
    _timing,
    _timing_gated,
    _aux_diagnostics,
    _bootstrap_median_diff,
)
from grokking_scaling_theory.sharpening import analyze_trace as sharpening_trace  # noqa: E402

MAX_TIMING_CHECKPOINTS = 1000  # memory + cost cap; timing is cadence-insensitive


def load_strided(npz_path: Path) -> TraceArrays:
    raw = np.load(npz_path)
    epochs = np.asarray(raw["epochs"], dtype=int)
    stride = max(1, int(np.ceil(len(epochs) / MAX_TIMING_CHECKPOINTS)))
    return TraceArrays(
        epochs=epochs[::stride],
        hidden=np.asarray(raw["hidden"][::stride], dtype=float),
        classes=np.asarray(raw["classes"], dtype=int),
    ), stride


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trace_dir", type=str, default="data/phase2_traces_v2")
    parser.add_argument("--arch", type=str, default="deep5",
                        help="arch prefix of the arm to adjudicate (e.g. deepnarrow)")
    parser.add_argument("--out", type=str, default=None)
    args = parser.parse_args()
    trace_dir = Path(args.trace_dir)
    out_path = args.out or f"analysis/{args.arch.upper()}_RESULTS.md"

    # ---- shallow concentration pool for D3 (final checkpoint only; cheap)
    shallow_conc: List[float] = []
    for npz in sorted(trace_dir.glob("trace_*.npz")):
        arch = json.loads(npz.with_suffix(".json").read_text())["config"]["arch"]
        if arch not in ("mlp", "noskip", "residual"):
            continue
        raw = np.load(npz)
        fc = fourier_concentration(
            np.asarray(raw["hidden"][-1], dtype=float),
            np.asarray(raw["classes"], dtype=int),
        )
        shallow_conc.append(fc["mean"])
        print(f"[shallow pool] {npz.name}: conc {fc['mean']:.3f}", flush=True)

    # ---- deep5 traces
    lines: List[str] = []
    lines.append(f"# {args.arch} Arm Results (amendments 6-7)")
    lines.append("")
    lines.append(
        "Generated by `scripts/adjudicate_deep5.py`. Decision rules D1-D4 "
        "per amendments 5-6; D_logic fits carry the amendment-4 sanity "
        "gate. Final-layer timing series strided 2x above 1500 checkpoints "
        "(disclosed cost control); spectral observables skipped (not part "
        "of the registered rules for this arm)."
    )
    lines.append("")
    lines.append("## Training outcomes")
    lines.append("")
    lines.append("| p | seed | grok epoch | censored | final val |")
    lines.append("|---:|---:|---:|:---:|---:|")

    per_run: List[Dict[str, object]] = []
    for npz in sorted(trace_dir.glob(f"trace_{args.arch}_*.npz")):
        meta = json.loads(npz.with_suffix(".json").read_text())
        cfg, res = meta["config"], meta["result"]
        tau: Optional[int] = res["grokking_epoch"]
        lines.append(
            f"| {cfg['modulus']} | {cfg['seed']} | {tau if tau else '-'} "
            f"| {'yes' if res['is_censored'] else 'no'} "
            f"| {res['final_val_acc']:.1f}% |"
        )

        print(f"[deep5] analyzing {npz.name}", flush=True)
        trace, stride = load_strided(npz)

        # canonical-layer series
        ls = d_logic_series(trace)
        fc = fourier_concentration(trace.hidden[-1], trace.classes)
        covered_any = bool(np.any(ls["fourier_covered"] + ls["qr_covered"] > 0))
        entry: Dict[str, object] = {
            "p": cfg["modulus"], "seed": cfg["seed"], "tau": tau,
            "stride": stride,
            "purity_final": float(ls["max_two_sided_purity"][-1]),
            "covered_any_final_layer": covered_any,
            "conc_final": float(fc["mean"]),
        }

        # D4 timings (grokked runs only) — while the strided trace is alive.
        if tau is not None:
            dvar = d_var_series(trace)
            t_dvar = _timing("D_var", trace.epochs, dvar, tau)
            s_raw = compute_order_parameters(trace, k=10, seed=0)
            t_sheaf = _timing("D_sheaf_B_raw", s_raw["epochs"], s_raw["d_sheaf_b"], tau)
            trp = project_pca(trace, d=64, fit_epoch=tau)
            s_pca = compute_order_parameters(trp, k=10, seed=0)
            del trp
            t_pca = _timing("D_sheaf_B_pca64", s_pca["epochs"], s_pca["d_sheaf_b"], tau)
            t_logic = _timing_gated("D_logic", ls["epochs"], ls["d_logic"], tau)
            entry["timings"] = {
                "D_var": t_dvar, "D_sheaf_B_raw": t_sheaf,
                "D_sheaf_B_pca64": t_pca, "D_logic": t_logic,
            }

        # aux layers (native cadence). _aux_diagnostics reads the npz itself
        # and only uses the passed trace's classes, so the strided trace is
        # a valid carrier.
        aux = _aux_diagnostics(npz, trace, tau)
        entry["aux"] = {
            k: {
                "purity": v["max_purity_final"],
                "covered_any": v["covered_any"],
                "conc": v["fourier_conc_mean"],
            }
            for k, v in aux.items()
        }
        entry["covered_any_any_layer"] = covered_any or any(
            v["covered_any"] for v in aux.values()
        )

        # Free the big canonical array before the sharpening pass (which
        # reloads the npz with its own memory-capped strides).
        classes_keep = trace.classes
        del trace
        entry["sharpening"] = [
            (lname, r, verdict) for lname, r, verdict in sharpening_trace(npz)
        ]
        per_run.append(entry)

    n = len(per_run)
    n_grokked = sum(1 for e in per_run if e["tau"] is not None)

    # ---- per-layer diagnostics table
    lines.append("")
    lines.append("## Per-layer cell diagnostics")
    lines.append("")
    lines.append("| p | seed | layer | purity | covered(any ckpt) | conc |")
    lines.append("|---:|---:|---|---:|:---:|---:|")
    for e in per_run:
        for lname, d in sorted(e["aux"].items()):
            lines.append(
                f"| {e['p']} | {e['seed']} | {lname.replace('hidden_','')} "
                f"| {d['purity']:.2f} | {'y' if d['covered_any'] else 'n'} "
                f"| {d['conc']:.2f} |"
            )
        lines.append(
            f"| {e['p']} | {e['seed']} | final | {e['purity_final']:.2f} "
            f"| {'y' if e['covered_any_final_layer'] else 'n'} "
            f"| {e['conc_final']:.2f} |"
        )

    # ---- D1 / D2
    d1_runs = sum(1 for e in per_run if e["covered_any_any_layer"])
    lines.append("")
    lines.append("## Adjudication")
    lines.append("")
    lines.append(
        f"- **D1 (cell formation)**: {d1_runs}/{n} runs with >= 1 covered "
        f"proposition in any layer => "
        f"{'POSITIVE' if d1_runs >= 5 else 'NEGATIVE'} (threshold 5/9)."
    )
    if d1_runs == 0:
        lines.append("- **D2**: moot (no coverage anywhere).")

    # ---- D3 (grokked only primary)
    deep_g = [e["conc_final"] for e in per_run if e["tau"] is not None]
    deep_all = [e["conc_final"] for e in per_run]
    if deep_g and shallow_conc:
        med, lo, hi = _bootstrap_median_diff(deep_g, shallow_conc)
        lines.append(
            f"- **D3 (Fourier vanishing, grokked deep5 only, n={len(deep_g)})**: "
            f"{args.arch} median {np.median(deep_g):.2f} vs shallow pooled "
            f"{np.median(shallow_conc):.2f}; diff {med:+.2f} [{lo:+.2f}, {hi:+.2f}] "
            f"=> {'SUPPORTED' if hi < 0 else 'not supported'}."
        )
    if len(deep_all) != len(deep_g) and shallow_conc:
        med, lo, hi = _bootstrap_median_diff(deep_all, shallow_conc)
        lines.append(
            f"  - secondary (all {args.arch} incl. censored, n={len(deep_all)}): "
            f"diff {med:+.2f} [{lo:+.2f}, {hi:+.2f}]."
        )

    # ---- D4 cascade
    lines.append("")
    lines.append("## D4: cascade timings (grokked runs)")
    lines.append("")
    lines.append("| p | seed | tau | op | t_trans | R^2 | amp | rel.err |")
    lines.append("|---:|---:|---:|---|---:|---:|---:|---:|")
    for e in per_run:
        if e["tau"] is None:
            continue
        for op, tm in e["timings"].items():
            tt = ("degen-gated" if tm.gated else "unclassif") if tm.t_transition is None else f"{tm.t_transition:.0f}"
            re_ = "-" if tm.rel_error is None else f"{tm.rel_error:.3f}"
            amp = "-" if tm.amplitude != tm.amplitude else f"{tm.amplitude:.3f}"
            lines.append(
                f"| {e['p']} | {e['seed']} | {e['tau']} | {op} | {tt} "
                f"| {tm.r2:.3f} | {amp} | {re_} |"
            )

    # ---- S-statistics replication
    lines.append("")
    lines.append("## Sharpening S-statistics replication (amendment 6 Part A on deep5)")
    lines.append("")
    lines.append("| p | seed | layer | S1 | S2a | S2b | verdict |")
    lines.append("|---:|---:|---|---:|---:|---:|---|")
    from collections import Counter
    s_verdicts = []
    for e in per_run:
        for lname, r, verdict in e["sharpening"]:
            s2a = f"{r.s2a_median_slope:+.3f}" if np.isfinite(r.s2a_median_slope) else "n/a"
            s2b = f"{r.s2b_onset_overtone:.3f}" if np.isfinite(r.s2b_onset_overtone) else "n/a"
            lines.append(
                f"| {e['p']} | {e['seed']} | {lname} | {r.s1_jaccard:.2f} "
                f"| {s2a} | {s2b} | {verdict} |"
            )
            s_verdicts.append(verdict)
    counts = Counter(s_verdicts)
    lines.append("")
    lines.append(
        "S-verdict counts: " + ", ".join(f"{k} x{v}" for k, v in counts.most_common())
    )

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"\nwritten: {out}")


if __name__ == "__main__":
    main()
